class AllStrings {

  AllStrings._();

  static const String confirmPassword = "confirmPassword";
  static const String password = "Password";
  static const String fullName = "Full Name";
  static const String keepLoggedIn = "Keep me Logged in";
  static const String forgotPassword = "Forgot Password";
  static const String next = "Next";
  static const String partnershipSubscription = "Partnership Subscription";
  static const String chnagePassword = "Change Password";
  static const String confirm = "Confirm";
  static const String signUp = "Sign Up";
  static const String orSignInWith = "Or Sign in with";
  static const String dotHaveAccount = "Don’t have an Account";
  static const String signUpHere = "Signup here";
  static const String createAccount = "Create an Account";
  static const String alreadyHaveAccount = "Already have an Account";
  static const String signInHere = "SignIn here";
  static const String give = "Give";
  static const String watchTheLive = "Watch The Live";
  static const String donateNow = "Donate Now";
  static const String theKakandeMinistries = "THE KAKANDE MINISTRIES";
  static const String showMore = "Show More";
  static const String about = "About";
  static const String donate = "Donate";
  static const String  donateOrOffering = "DONATION, TITHE OR OFFERING";
  static const String ourMission = "Our Mission";
  static const String donateTo = "Donate To";
  static const String amount = "Amount";
  static const String usd = "USD";
  static const String frequency = "Frequency";
  static const String recurring = "Recurring";
  static const String oneTime = "One Time";
  static const String recurrence = "Recurrence";
  static const String twiceMonthly = "Twice Monthly";
  static const String proceed = "Proceed";
  static const String bible = "Bible";
  static const String name = "Name";
  static const String emailAddress = "Email Address";
  static const String age = "Age*";
  static const String prayerFor = "Prayer For";
  static const String streetAddress = "Street Address";
  static const String browseFile = "Browse File";
  static const String selectFileTitle = "Select File Title";
  static const String type = "Type:";
  static const String live = "LIVE";
  static const String now = "NOW";
  static const String phone = "Phone";
  static const String becameAPartner = "The Kakande Ministries\n \n What a privilege it is to serve Him during these exciting times! God is accomplishing great and mighty things, and that’s why I want to personally invite you to become a Covenant Partner so that, together, we can fulfill the Great Commission and win the world in His mighty name.\n\n As a partner in this ministry, you will be making a difference in lives around the world, and what a privilege it is to serve Him during these exciting times.\n\n “And this gospel of the kingdom shall be preached in all the world for a witness unto all nations; and then shall the end come.” — Matthew 24:14 \n \nWhen I minister to the multitudes, my partners are there with me. When I go to the nations through television and crusades, and when we see multiplied tens of thousands of men, women, and children weeping as they accept Jesus in their lives, you will be blessed with an eternal harvest for the seed you have sown.";
  static const String testimonials = "TESTIMONIALS";
  static const String testimonialsText = "Jesus Christ is the same, yesterday, today and forever Hebrews 13:8. He still saves, heals and delivers. \n\n Be blessed as you watch amazing faith building testimonies of people who were prayed for by Prophet Samuel Kakande.";
  static const String becamePartner = "BECOME A PARTNER TODAY";
  static const String rememberMe = "Remember me";
  static const String mp3mp4 = "MP3, MP4, jpg, png ";
  static const String writeYourPrayer = "Write your Prayer";
  static const String prayerRequest = "PRAYER REQUEST";
  static const String callNow = "Call now";
  static const String address = "Address";
  static const String submit = "Submit";
  static const String mainAdrees  = "Mulago, Ku Round About. PO BOX 161616.\n Kampala Uganda.";
  static const String contactUs = "CONTACT US";
  static const String sendAMsg = "SEND A MESSAGE";
  static const String addTestimonials = "Add Testimonials";
  static const String prayerNumber = "+256 200 414550";
  static const String sendPrayerRequest = "Send Prayer Request";
  static const String phoneNumber = "Phone Number";
  static const String firstName = "First Name";
  static const String lastName = "Last Name";
  static const String country = "Coountry";
  static const String countryOfResidence = "Country of Residence";
  static const String physicalAddress = "physicalAddress";
  static const String yourPhysicalAddress = "Your physical address";
  static const String partnershipTire = "Partnership tire- Monthly subscription";
  static const String paymentMode = "Payment method";
  static const String comment = "Comment (optional)";
  static const String sendUsRequest = "Send us Prayer Request and we will stand steadfastly in faith with you! Call us or simple fill the form.";
  static const String theKakandeComittedTo = "THE KAKANDE MINISTRIES COMITTED TO";
  static const String adboutFirstContent = "Voluptatem dolorem sed inventore incidunt ut commodi doloremque id dolores libero nam nemo neque quo delectus tenetur est placeat placeat. Ut repellendus consectetur aut ipsum aspernatur sit dolorem sunt? At quod ipsum et iusto dolor non suscipit reiciendis sed necessitatibus totam eos rerum consequuntur est sequi minus hic enim ducimus. Aut provident ullam hic placeat fugiat At officiis voluptatum.";
  static const String hintText = "The Kakande Ministries is a Life Changing Ministry taking the Gospel of our Lord and Savior Jesus Christ to the four corners of the world (Matthew 24:14)";

//

  static const String IMEI_NO = "";
  static const String TOKEN = "";
  static const String USER_MOBILE_NO = "";
  static const String welcomeBack = "This app is for the use of conductor to mange trip";
  static const String loginMsg = "Please eVerify Yourself with Registered Mobile Number and Trip Key Received in SMS as a result of Trip Chart Generation ";
  static const String mobileNo = "Mobile number";
  static const String signIn = "Log in";
  static const String startTrip = "Start Trip";
  static const String stopTrip = "Stop Trip";

}